### Fetch all tasks

GET http://localhost:3200/tasks
Content-Type:application/json

### create a task

POST http://localhost:3200/tasks
Content-Type:application/json

   {
        "title": "Dog park",
        "date": "04/13/2024",
        "description": "Take baby to dog park to play",
        "priority": "high",
        "status": "todo"
    }


### update a task

PUT http://localhost:3200/tasks
Content-Type:application/json

{
    "id":"fd50e4a9-62ce-4534-8c43-19e40724554a",
    "status":"inProgress"
}